### ISSUE TITLE
Summary entered on edit case page displayed as one paragraph on case home page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#102]
When I enter a paragraph in the summary section of the "edit case" page and it has more than one paragraph, that text is shown as one paragraph in a jumble on the "show case" page.

Here's a screenshot
<img width="1280" alt="entering_summary_data" src="https://cloud.githubusercontent.com/assets/13509/9424015/9a172fcc-48aa-11e5-8255-07aca07a14d2.png">
 of the edit case page and one of the summary
<img width="1280" alt="summary_as_one_paragraph" src="https://cloud.githubusercontent.com/assets/13509/9424017/a647ac5e-48aa-11e5-9bd7-b01797e97060.png"> shown afterwards.

If the user enters more than one paragraph, they should be able to see the distinct paragraphs on the page.

**Comment by campgurus** [comment]
Maybe we should consolidate all issues with the Article new/edit form UI that could be better.  This is a fundamental feature that needs to be easy to use.

**Comment by campgurus** [comment]
I think this was fixed on production with the addition of ckeditor.
