### ISSUE TITLE
Summary, Overview & Litigation sections are too small on edit page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#103]
When editing a case, these three sections for entering data are too small to enter input. Here's a screenshot with an example:
<img width="1280" alt="entering_summary_data" src="https://cloud.githubusercontent.com/assets/13509/9424058/6d0ebe62-48ac-11e5-971c-ef93cdc0ee61.png">

That aspect of entering user data can decidedly be improved. We should discuss the nature of the changes that need to be made.

**Comment by campgurus** [comment]
Additionally, we need to make adding html tags which are already parsed less manual. e.g. An editor should be able to highlight a phrase and click a link icon to create an anchor tag with a url, or add basic styling to text.  There are a couple gems that may help with this including:

* http://www.rubydoc.info/gems/phrasing/3.2.9#Installation
* http://jejacks0n.github.io/mercury/

**Comment by campgurus** [comment]
I think this is solved with ckeditor as well. reopen if needed.
