### ISSUE TITLE
"Victims" should be renamed "Subjects"

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#112]
We've had a long discussion about using "Subjects" instead of "Victims", yet the language about which is which is confusing
<img width="372" alt="screenshot 2015-08-23 06 54 12" src="https://cloud.githubusercontent.com/assets/13509/9427935/d1a682b2-4963-11e5-8253-26681a1a3a57.png">

All instances of "Victims" should be replaced with "Subjects"

**Comment by campgurus** [comment]
Fixed here: 24df7ad8803dab66a5ba8803be21fdb3db19da3a
