### ISSUE TITLE
Mailbox Reply gives no indication of why a user is receiving it

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#118]
When a user receives a message from the site, there is NO indicator that this comes from EBWiki.

Here's a screenshot of the message:
<img width="1280" alt="screenshot 2015-08-23 07 52 51" src="https://cloud.githubusercontent.com/assets/13509/9428102/3d6d5ee6-496c-11e5-8363-5163172915e3.png">

In particular:
- [x] The domain comes from mailboxer.com, not ebwiki.org
- [ ] The copy says "you have receive a new reply", but doesn't say what they have replied to. 
- [ ] A specific link to the message itself would be helpful. 

It isn't until the ebwiki.org link at the bottom of the message when the user realizes that they're receiving something from the site.

**Comment by campgurus** [comment]
code for these fixes is in mailboxer_fixes:

fixed the domain by editing the mailboxer initializer file.

**Comment by campgurus** [comment]
Though the gem's readme doesn't mention it, editing the Mailboxer views is documented here: http://adminuser.org/customizing-mailboxer-mailer-views/
