### ISSUE TITLE
Article Form needs explanation

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#120]
Editors adding or updating articles are getting confused by the lack of instruction.  we need to add tooltips or other visual aids for editors.

**Comment by campgurus** [comment]
These tooltips are up on production. However, I have not been able to get a working rspec to confirm that the tooltips are available when the user opens the form.  Here is where I have left off for now:

the spec:

describe 'articles/edit.html.erb' do
    it 'renders the form for a new article creation' do
      assign(
        :article,
        mock_model(Article).as_new_record.as_null_object
      )
      render
      rendered.should have_selector('form',
        method: 'post',
        action: articles_path
      ) do |form|
        form.should have_selector('input', type: 'submit')
      end
    end
end

the trace:

Failures:

  1) articles/edit.html.erb renders the form for a new article creation
     Failure/Error: render
     ActionView::Template::Error:
       wrong constant name Article#<RSpec
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/form_builder.rb:620:in `const_get'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/form_builder.rb:620:in `attempt_mapping'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/form_builder.rb:571:in `find_mapping'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/form_builder.rb:502:in `find_input'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/form_builder.rb:112:in `input'
     # ./app/views/articles/_form.html.erb:20:in `block in _app_views_articles__form_html_erb___1416665284705015232_70184360696500'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/capture_helper.rb:38:in `capture'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/form_helper.rb:444:in `form_for'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
     # ./.bundle/gems/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
     # ./app/views/articles/_form.html.erb:1:in `_app_views_articles__form_html_erb___1416665284705015232_70184360696500'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:333:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:143:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/partial_renderer.rb:309:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:47:in `render_partial'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/rendering_helper.rb:35:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/test_case.rb:199:in `render'
     # ./app/views/articles/edit.html.erb:12:in `_app_views_articles_edit_html_erb__2946212740254641461_70184340443940'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:145:in `block in render'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:333:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/template.rb:143:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/renderer/renderer.rb:23:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/helpers/rendering_helper.rb:32:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/test_case.rb:199:in `render'
     # ./.bundle/gems/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/test_case.rb:120:in `render'
     # ./spec/views/articles/edit.html.erb_spec.rb:9:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:76:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:75:in `block (2 levels) in <top (required)>'

**Comment by campgurus** [comment]
should we close this?

**Comment by trystant** [comment]
Why is this closed? Let's schedule a time to put together a spec for this.

**Comment by campgurus** [comment]
This issue is included in #147. we should consolidate where we have duplication. SHould have made the reason more plain, not just that i don't want to do view specs.

**Comment by trystant** [comment]
I added a spec to confirm the existence of the text required for the tooltip, which I just added with commit 1368fbf. We can close this ticket.
