### ISSUE TITLE
Add password security to staging site

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#124]
Something like this should work:

# config/environments/staging.rb
MyApp::Application.configure do
  config.middleware.insert_after(::Rack::Lock, "::Rack::Auth::Basic", "Staging") do |u, p|
    [u, p] == ['username', 'password']
  end

  #... other config
end

**Comment by trystant** [comment]
As long as we have the ENV variables protected as in the rest of the [blog post](https://olemortenamundsen.wordpress.com/2011/04/05/ruby-secure-staging-environment-of-your-public-app-from-users-and-bots/), that would work.
