### ISSUE TITLE
Resolve N+1 query discovered by oink on home page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#127]
Awhile back we discovered the "oink" gem and used it to profile our app. The javascript popup that appears offers advice that should be taken in order to remove the N+1 query, even if pagination reduces the number of objects returned.

<img width="1280" alt="screenshot 2015-08-25 11 47 20" src="https://cloud.githubusercontent.com/assets/13509/9471828/2a369120-4b20-11e5-9a39-86fd8eac3537.png">

**Comment by rlgreen91** [comment]
This issue has been addressed.  Additionally, the Bullet gem is now used to identify all N+1 queries in development and prior to merging them into the production database.
