### ISSUE TITLE
Long comments leave lots of space in the center of the case's page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#128]
If a lot of text is put in the comments, it currently pushes the related cases far down, leading to lots of empty space on the page. We need to figure out what to do with comments; whether to have them after the case information, or on a separate page, or on a modal over the case.

<img width="1280" alt="screenshot 2015-08-25 12 02 45" src="https://cloud.githubusercontent.com/assets/13509/9472124/62807356-4b21-11e5-9583-60eb1ef3a52f.png">

**Comment by campgurus** [comment]
fixed on production
