### ISSUE TITLE
Fix typo in meta description

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#141]
in `app/views/articles/index.html.erb`, the description has a typo:

`EBWiki is a new web application woring to harness the power of community to end bias in law enforcement that has led to disparate treatment of people of color with tragic results.`

**Comment by campgurus** [comment]
Is this resolved?

**Comment by trystant** [comment]
Yep. It's on production.

**Comment by campgurus** [comment]
Cool. Should we close it?
