### ISSUE TITLE
Add Analytics page to share site analytics

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#145]
This issue is aimed at developing an analytics view that will help us improve the site based on how visitors interact with the content and features. Some or all of this content may be appropriate for public viewing.

Things we could track on an analytics page:
* number of visitors
* trending cases ranked by recent engagement (e.g. views, follows, comments, edits in the past 7 days) 
* geographical distribution of site visitors
* number of editors
* cases updated

code for this is in the site_analytics branch

**Comment by campgurus** [comment]
I don't remember if this is working or not.

**Comment by campgurus** [comment]
in terms of building the dashboard, thought this might be a useful tutorial: https://medium.com/@jatescher/creating-a-metrics-dashboard-with-ember-js-bootstrap-and-rails-part-1-b11cf922408d#.upammlrw7

**Comment by campgurus** [comment]
With the inability to parse Ahoy Events, I still think we can have a decent analytics page viewable by the public.  We may decide to remove recently updated cases from the Home Page and include it on the public analytics page.  Alternatively, maybe it makes sense to include all of the analytics at the bottom of the home page. What we will miss without Ahoy is the ability to view and analyze clicks, and probably the ability.  Here are some of the things I think we could display without using Ahoy::Events:

* number of visitors by location
* Visitors by date
* Number of Vistors in last 30 days
* Most Followed cases
* Recent Case Comments
* Recently Updated
* Most Viewed Cases (reqs Ahoy)

**Comment by campgurus** [comment]
Thinking we can use Google Analytics for some stats until we figure out how to parse the data we are already gathering. Here is a tutorial on how to access Google Analytics with ruby:

http://willschenk.com/pulling-data-out-of-google-analytics/

**Comment by campgurus** [comment]
A nice sample layout:

code: https://github.com/iogbole/gentelella_on_rails/commit/12c84dee8e4bc9c365acb2b982bb30c50a8116ff

demo:
https://colorlib.com/polygon/gentelella/index.html

**Comment by campgurus** [comment]
I think it is important to consider the analytics page in terms of our goals for EBWiki and what we are trying to achieve in terms of user behavior.  That should drive the metrics we track on the analytics page. I know we have discussed this in other places, but I think it doesn't hurt to have it here as well.

In short, at this point, we want people to view and engage with our content. Tracking engagement means:

* site visits
* cases viewed
* cases followed
* unique followers
* user sign ins
* newsletter sign-ups
* email updates
* cases edited
* unique editors

I think if we track these things we will have a good view into how well we are engaging users with our content. In the meantime, we should prioritize which of these is most important to determine where to place the stats on the page. We are doing this implicitly, but we could benefit from a more purposeful approach.

**Comment by trystant** [comment]
I think that this is no longer a single issue, and should be split into separate tickets with the tag "analytics" and linked to this issue. I also think that one of the first issues would be to have a comprehensive analytics approach.

**Comment by campgurus** [comment]
closing this.  As @trystant mentioned, any future additions to the current production analytics page should be the subject of separate issues.
