### ISSUE TITLE
Make Edit article form more user friendly

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#147]
The editors form is a central feature of the app, it needs to be easy for the editors to use.

I think we need to have at a baseline level:
- [ ] clear separation of the different elements of the form
- [ ] more directions on how to use the form
- [ ] graceful errors when editors make mistakes on the form
- [ ] congratulatory messages to editors who update or add cases
- [ ] clean up display of associated models, e.g. no need to display all links
- [ ] Change date format to American-style MM/DD/YYYY
- [ ] Allow large text fields to be styled and editing to be perceived and rendered as expected
- [ ] Add tags field to form

this is somewhat of a working list summarizing issues with the form.  @trystant let  me know if I should instead create separate issues with appropriate labels.

**Comment by campgurus** [comment]
I am closing this issue as vague and/or outdated.

**Comment by trystant** [comment]
Fine. I'm going to open more specific tickets about this moving forward.

On Mon, May 9, 2016 at 5:55 AM, campgurus <notifications@github.com> wrote:

> Closed #147 <https://github.com/BOWiki/BOW/issues/147>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/147#event-654175284>
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant
