### ISSUE TITLE
301 redirect needed for old herokuapp.com address

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#153]
This is a placeholder so I don't forget this until I have time to come back and add details. Relates to webmaster and discrepancy between indexed pages vs sitemaps

This article gives guidance on what we need to do: https://builtvisible.com/change-of-address/

**Comment by campgurus** [comment]
I think this issue may have been resolved by creating a new webmaster account. pages seem to be indexing appropriately.

**Comment by trystant** [comment]
Well, I can still access http://blackopswiki.herokuapp.com/. 

Do we want that to automatically go to http://ebwiki.org? I believe that we probably do.

**Comment by campgurus** [comment]
i agree. I can research how to do it if you want.

**Comment by trystant** [comment]
Here's an option from within Rails: https://github.com/cwninja/rack-force_domain

**Comment by campgurus** [comment]
Not sure how to do this but I want to bump this.  the herokuapp address will always be active, but we should redirect to the ebwiki.org url

**Comment by campgurus** [comment]
Fixed on production
