### ISSUE TITLE
.gitignore needs to be updated

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#216]
The .gitignore is on the incomplete end. This allows built artifacts to mess up things like [TravisCI builds](https://travis-ci.org/BOWiki/BOW/builds/80523432). This should be fixed by:

- [x] - Using a standard .gitignore from [Github](https://raw.githubusercontent.com/github/gitignore/master/Rails.gitignore)
- [x] - Confirming that each entry is appropriate for our project
- [x] - Removing items from github that are in .gitignore
- [x] - Publishing .gitignore

**Comment by campgurus** [comment]
is this merged to master?  SHould this issue be closed?

**Comment by trystant** [comment]
Yes. If you click on the commit referenced in the issue, you'll see that that is on the master branch. It should also be in the repo now.

**Comment by campgurus** [comment]
I added back .env and public/uploads to the git ignore file. and committed to master. closing this.
