### ISSUE TITLE
Gender Orientation needs to be expanded

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#251]
Right now we only have three gender designations. Facebook has 51, for example. We should expand this. Here's a guide/list:

http://itspronouncedmetrosexual.com/2013/01/a-comprehensive-list-of-lgbtq-term-definitions/

**Comment by campgurus** [comment]
Do we really want to give our editors a choice of 51 gender identifiers to specify essentially if a subject is male female or trans? I think it could be much more confusion than it's worth.  Even if we decided that it was worth doing.  This kind of detailed info has not been available in any of the several hundred cases I have already input.

I think this one should be on the back burner.

**Comment by trystant** [comment]
Facebook does it and it wouldn't take long.

**Comment by trystant** [comment]
Also, here's a case on our site

http://ebwiki.org/articles/rickie-shawatza-hall



On Tue, Mar 22, 2016 at 11:35 PM, Mark Nyon <mark@grandkru.com> wrote:

> Facebook does it and it wouldn't take long.
> On Mar 22, 2016 11:10 PM, "campgurus" <notifications@github.com> wrote:
>
>> Do we really want to give our editors a choice of 51 gender identifiers
>> to specify essentially if a subject is male female or trans? I think it
>> could be much more confusion than it's worth. Even if we decided that it
>> was worth doing. This kind of detailed info has not been available in any
>> of the several hundred cases I have already input.
>>
>> I think this one should be on the back burner.
>>
>> —
>> You are receiving this because you were assigned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/BOWiki/BOW/issues/251#issuecomment-200146644>
>>
>


-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by trystant** [comment]
And two more: 
http://ebwiki.org/articles/duanna-johnson
http://ebwiki.org/articles/kayla-moore

**Comment by campgurus** [comment]
All of these cases are covered within the 3 designations we already have.  I don't think this is necessary or a good idea.

**Comment by trystant** [comment]
I don't see any way this would be less than a "good" idea. The three designations remain, and other options are available. It would take less time  to add those than we've spent going back and forth about this.

In any case, it's off your plate. I'll do it. It'll be my first priority.

**Comment by trystant** [comment]
This is now in production.
