### ISSUE TITLE
Enable non-youtube videos

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#255]
Currently, we only have the ability to embed youtube videos, so important videos get missed.  here is a example of one video we could not accommodate: http://newsone.com/3203425/footage-of-matthew-ajibades-struggle-with-police-released-during-trial/

**Comment by campgurus** [comment]
Although we have now enabled Vimeo videos like in this case: http://ebwiki.org/articles/george-golden, I will leave this issue open since there are likely many other types of videos we will want to embed.

**Comment by trystant** [comment]
Or you can close this one, and open a ticket for each additional type of
embedded video

**Comment by campgurus** [comment]
whate'r you think is best

**Comment by campgurus** [comment]
ok closing this. We will add issues as we find types of videos we want to enable.
