### ISSUE TITLE
Geocoder providing incorrect results to Google maps in some cases

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#3]
ege Sherman Byrd is showing up on the map in the UK, should be in Chester, Pennsylvania, USA.  May need to add country and zip code fields to Article model

**Comment by campgurus** [comment]
I attempted on local machine to add "country field" and also added zip code to "full_address" method for geocoding, but e.g. Fednel Rhinvil still shows in Salisbury, UK instead of Salisbury, MD.  Next solution may be to change config from using google to use bing or somethings else.

**Comment by trystant** [comment]
Changing tools is premature. You don't know what other issues will be raised by using another provider. I'd start with listing all the problematic addresses, determine what's the nature of the error involved, and that might point you towards a solution.

**Comment by campgurus** [comment]
I did not change tools away from geocoder, but i edited the initializer to use bing for geolocation instead of the default which is Google.  The change had no effect that I could discern.

**Comment by campgurus** [comment]
I think I may see the issue with this.  we are geocoding by full_address, which is a method that returns:
"#{address} #{city} #{state} #{zipcode} #{country}"

'state' is returning a model object.  should be 'state.name' instead

**Comment by campgurus** [comment]
fixed/closed

**Comment by campgurus** [comment]
Reopening this issue.  Geocoder works with the fix described above, changing article full_address method to reference "state.name" instead of  "state".  However, this causes a bunch of rspec tests to fail, so we are currently back to referencing the associated state object.
