### ISSUE TITLE
Add Agencies and Officers models and associations to Cases

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#320]
We are currently removing the old Agencies and Officers models to streamline our code.  These models are not being used in the current code so @trystant is streamlining them.  This issue is being added to remind us what we were intending to do with these models, so we can implement them correctly when the time comes.

Specifically, we want to have an officers model and an agencies model, so that we can track the involvement of both of those groups in the various cases.  e.g. which police agencies are responsible for the majority of cases.  We also want to make it easy for the user to search for cases by agency or officer.

Ultimately, we want a show view for individual officers and departments/agencies that provide the cases they have been involved in as well as information about who is in charge and how to contact them.

**Comment by trystant** [comment]
These need to be split into two separate tickets, and some more details on how this pans out on the site in each case.

**Comment by trystant** [comment]
Also, this is something that is way off in the future. We have some housecleaning to do before we can or should approach these again.
