### ISSUE TITLE
Error trying to get to Visits(ahoy) table in rails _admin

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#33]
error when trying to reach Visits table in rails_admin Unsupported field datatype: uuid

**Comment by trystant** [comment]
First, what is the stacktrace associated with this error?

Second, have you looked at the rails_admin issues, in particular [this](https://github.com/sferik/rails_admin/issues/1681) one?

**Comment by campgurus** [comment]
fixed.  thanks.  closing this.
