### ISSUE TITLE
when multiple cases have the same city and state, only one pin shows.

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#34]
Not sure if there is a solution to this.

**Comment by trystant** [comment]
@campgurus I believe that you've resolved this issue; there are now number counts on cases, isn't that correct?

**Comment by trystant** [comment]
I believe that this fix is now in place. We can close this ticket.

**Comment by trystant** [comment]
Evidence: <img width="1280" alt="screenshot 2015-10-06 05 06 36" src="https://cloud.githubusercontent.com/assets/13509/10304420/0b18383c-6be8-11e5-9600-bcd177544e60.png">
