### ISSUE TITLE
Edit Profile Page has wrong h1 language

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#371]
page header reads "Edit Article". should be "Edit your User profile" screenshot attached

<img width="897" alt="screen shot 2016-02-29 at 6 11 05 am" src="https://cloud.githubusercontent.com/assets/1260659/13392867/b222df48-deab-11e5-9397-65f1769bf32e.png">

**Comment by trystant** [comment]
Cool, that is an easy fix. You want to take this?

**Comment by campgurus** [comment]
I pushed the change to the master.  I can push it to production as well

**Comment by trystant** [comment]
Nothing to it but to do it!

On Mon, Feb 29, 2016 at 10:14 AM, campgurus <notifications@github.com>
wrote:

> I pushed the change to the master. I can push it to production as well
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BOWiki/BOW/issues/371#issuecomment-190252659>.
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by campgurus** [comment]
done. closing this.
