### ISSUE TITLE
Possibly remove the paragraph from the front page

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#375]
It feels simply like there are too many words. The second sentence may be unnecessary except that it prominently links to the About Us page.

**Comment by trystant** [comment]
I agree with the word count being too high. I have a friend who's a
copywriter. She can take another look at it and offer suggestions.

**Comment by campgurus** [comment]
Closing after recent edits.  H/e this is obviously an issue that will be ongoing.
