### ISSUE TITLE
Geocoder for articles not using state field

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#38]
articles are geocoded by the article.full_address method.  That method references the state object:

def full_address
	"#{address} #{city} #{state}"
end

As a result, an article in Miami, OH, geocodes as if in Miami, FL.  Instead the full_address method should reference state.name.

def full_address
	"#{address} #{city} #{state.name}"
end

However, fixing the method causes multiple rspec failures.  Here is an example:

 1) ArticlesController#index assigns all articles to @articles
     Failure/Error: let(:articles) { FactoryGirl.create_list(:article, 4) }
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./app/models/article.rb:34:in `full_address'
     # ./.bundle/gems/ruby/2.2.0/gems/geocoder-1.2.8/lib/geocoder/stores/base.rb:99:in `do_lookup'
     # ./.bundle/gems/ruby/2.2.0/gems/geocoder-1.2.8/lib/geocoder/stores/active_record.rb:259:in `geocode'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:239:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:239:in `block in halting'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `block in call'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `each'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:506:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_validation_callbacks'
     # ./.bundle/gems/ruby/2.2.0/gems/activemodel-4.2.1/lib/active_model/validations/callbacks.rb:113:in `run_validations!'
     # ./.bundle/gems/ruby/2.2.0/gems/activemodel-4.2.1/lib/active_model/validations.rb:334:in `valid?'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:58:in `valid?'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:83:in `perform_validations'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/validations.rb:43:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `block in save!'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
     # ./.bundle/gems/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/transactions.rb:291:in `save!'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # ./.bundle/gems/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:166:in `instrument'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block (2 levels) in define_list_strategy_method'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `times'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `each'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `map'
     # ./.bundle/gems/ruby/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
     # ./spec/controllers/articles_controller_spec.rb:4:in `block (2 levels) in <top (required)>'
     # ./spec/controllers/articles_controller_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:77:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `call'
     # ./.bundle/gems/ruby/2.2.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:76:in `block (2 levels) in <top (required)>'

**Comment by campgurus** [comment]
still not using the state name in geolocation.  as a stopgap, geocoder now has access to zip code as well.  adding a street address nearby and zip code seems to allow geo coder to work without error.

**Comment by trystant** [comment]
The article factory has an example of how to associate with a subject.

Also, the "[associations](https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#associations)" section of the factory_girl documentation has some examples that are worth trying out. This one, in particular:

```
factory :article do
  # ...
  state
end
```

**Comment by trystant** [comment]
Also, if the geocoder has access to a zip code, then the requirement for more specific location is satisfied, is it not?
