### ISSUE TITLE
Main Articles Map Shows only 12 cases

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#387]
Pagination in defining @articles seems to be limiting the map to showing 12 cases at a time.  I think we need to separate some of the logic combined for efficiency in the case_filter concern.

**Comment by campgurus** [comment]
There are few visitors who actually look at the map, but i think we should go ahead and revert the changes that caused this error. Maybe we can just go back to the less elegant, less DRY code that worked until we have a fix?

**Comment by trystant** [comment]
I'd rather find a solution, because reverting that would be a fair amount of work. I'm looking at this now.

**Comment by trystant** [comment]
So, there's a solution in place, all markers are available now. We can open another ticket for the map zoom level, and this is done.
