### ISSUE TITLE
Make links open in a new tab

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#43]
Currently clicking on an external link causes the user to lose the original BOW page.  Instead, it should open a new link with the new page.

**Comment by trystant** [comment]
Do you want all links from the articles to open up a new window, or only certain ones?

**Comment by trystant** [comment]
@campgurus Do you have an opinion on this?

**Comment by campgurus** [comment]
I think all external links should open in a new window.
On Jul 20, 2015 6:00 AM, "Mark Nyon" <notifications@github.com> wrote:

@campgurus <https://github.com/campgurus> Do you have an opinion on this?

—
Reply to this email directly or view it on GitHub
<https://github.com/BOWiki/BOW/issues/43#issuecomment-122830884>.

**Comment by campgurus** [comment]
fixed some time ago.  links at the end of the show page all open in new tabs.  Links within the content fields redirect away from EBW however.
