### ISSUE TITLE
Change the sendgrid password

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#44]
The sendgrid password has been shown in Travis builds; it should be changed.

**Comment by campgurus** [comment]
SendGrid indicates that because this was done as an add-on to heroku, we cannot change the password.  I will confirm that we need to set this up anew directly with SendGrid to chnage the pw.

**Comment by trystant** [comment]
@campgurus I've removed and added the sendgrid addon, which should change the application. Here's a question; is sendgrid currently being used?
