### ISSUE TITLE
Geocoder gives wrong results for User lat/long

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#477]
We currently use the [geocoder gem](https://github.com/alexreisner/geocoder) to find lat/longs for cases based on address information, whcih seems to work fine.

We attempt to geocode the User model based on the user's ip address, which is not providing accurate results. Not urgent, but it is a bug.  We may want to consider an alternative gem if we can't figure it out.

**Comment by trystant** [comment]
I'm in favor of disabling the user functionality until we implement a switch that allows the user to choose whether the IP is stored or not.
