### ISSUE TITLE
Strange formatting in content section

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#490]
see eg : http://ebwiki.org/articles/alton-reaves.

can't figure out how to adjust text size/line spacing etc.

**Comment by trystant** [comment]
All you need to do is specify the font size in the edit section. If you check, I've made the size smaller.
You can specify paragraphs by pressing return. This section works just like word or another editor.

**Comment by campgurus** [comment]
the line spacing still looks off.  do you know how to fix that?

**Comment by trystant** [comment]
Yeah, it's a matter of fiddling with the editor. This isn't an application-level problem though. I'm closing this bad boy.
