### ISSUE TITLE
ActiveAdmin User Edit page results in 500 error

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#5]
When I try to access a user edit [url](http://blackops-staging.herokuapp.com/admin/user/10/edit) through the admin, I get the following error:
![screenshot 2015-06-06 22 50 44](https://cloud.githubusercontent.com/assets/13509/8022425/a90693c6-0c9e-11e5-8a41-2d9ac84ee80d.png)

**Comment by campgurus** [comment]
Looking at the logs, I think this relates to Storytime which uses the existing user model. Somehow we end up in a processing loop until Heroku times out.

**Comment by campgurus** [comment]
After removing storytime, this issue seems to be gone.  closing this.
