### ISSUE TITLE
Need to disable send emails from staging

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#521]
to avoid sending emails to real followers while testing functionality on staging and locally. For now, I just deleted all follows form the staging db

**Comment by trystant** [comment]
This is easy. Move the SMTP setting from `/config/environment.rb` to `/config/environments/production.rb` and then add this line in `/config/environments/staging.rb`:

```
config.action_mailer.delivery_method = :test
```

**Comment by trystant** [comment]
This is in production
