### ISSUE TITLE
Adjust default image to include name of article.subject

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#532]
we have had several comments from users suggesting this step, and one editor has begun adding makeshift default images. This is aimed at making a more palatable default image and making life easier for editors who will no longer need to create one off images.

**Comment by campgurus** [comment]
This is on production.  Here is a link to the tutorial used in adding a text overlay to an image in bootstrap: http://javatechig.com/bootstrap/how-to-display-text-overlay-on-a-responsive-image-in-bootstrap

**Comment by trystant** [comment]
So, while looking at the images on staging, I ran into this:
<img width="234" alt="screenshot 2016-05-10 20 37 37" src="https://cloud.githubusercontent.com/assets/13509/15166663/273e73f2-16ef-11e6-8167-45f338e48427.png">

We should make sure that the second name disappears.

**Comment by campgurus** [comment]
Fix on production.
