### ISSUE TITLE
Google Maps is failing suddenly

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#543]
Suddenly all maps on all of the pages are failing to load.  it appears that the place where google is hosted has changed and we need to adjust. Below is what it looks like now:

<img width="1257" alt="screen shot 2016-05-13 at 11 05 50 am" src="https://cloud.githubusercontent.com/assets/1260659/15269027/4cf25356-19c0-11e6-81fd-5c2853ad8b69.png">

The issue was memorialized in the gem doc here including instructions for how to fix it:

https://github.com/apneadiving/Google-Maps-for-Rails/issues/514

**Comment by trystant** [comment]
The solution I've seen so far includes using git submodules, which we do not use and will not use as a part of this project. I'm going to check for alternatives.

**Comment by campgurus** [comment]
@trystant fixed this on production
