### ISSUE TITLE
Hitting limits of the Google geocoder api

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#56]
I may try switching us to bing instead which has higher limits and is also a bit faster.

**Comment by campgurus** [comment]
I haven't seen this issue in  the past month but I haven't done any further work on it.

**Comment by trystant** [comment]
Well, it looks like the address limits are 2,500 addresses per day according to the [Google](https://developers.google.com/maps/documentation/geocoding/usage-limits) page. Considering the way that the app is constructed now, I'd find it hard to imagine us hitting that limit anytime soon. This merits a close unless something changes, IMO.
