### ISSUE TITLE
Map does not seem to reflect all cases

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#582]
This may be minor, but when I look at this map, the number of pins totals about 1850 cases. However, Articles.count = 2088.  Trying to figure out if this is a bug, recognizing it may be nothing.
<img width="472" alt="screen shot 2016-06-03 at 9 49 30 am" src="https://cloud.githubusercontent.com/assets/1260659/15780673/dad4d440-2970-11e6-99cd-434e377176d2.png">

**Comment by campgurus** [comment]
Nevermind.  I think this is because ~220 cases have no lat/long. Closing this.

**Comment by campgurus** [comment]
Need to adjust the count at the top of the map page to only include cases with a lat and long value as those are the only ones that will appear on the map.

**Comment by trystant** [comment]
How about we find Lat/long for those cases?

**Comment by campgurus** [comment]
We will do our best, but addresses initially input by editors may not have enough detail to generate a lat long, so for a period of time until we get to it, the number will not be accurate without the conditional that discounts those records.

**Comment by campgurus** [comment]
closing this.
