### ISSUE TITLE
Heroku Memory Exceeded

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#6]
The Heroku instances are exceeding their memory and are being constantly killed and recycled. We need to figure out why this is occurring:

2015-06-07T02:52:37.067350+00:00 heroku[web.1]: Process running mem=2632M(514.1%)
2015-06-07T02:52:37.067350+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)

**Comment by trystant** [comment]
The best thing to do is try to figure out the exact reason why the memory bottleneck is occurring.

**Comment by trystant** [comment]
I'm taking a look at the dev app using the [bullet](https://github.com/flyerhzm/bullet) gem to see if we have any greedy queries in the mix.

**Comment by campgurus** [comment]
cautiously closing this after following sugggestions from Heroku support:

"Hi there,

I see it seems to settle into R14 errors under little traffic, that's problematic. Running oink in production all the time is definitely not recommended, so consider turning it off it is running in production.

Another simple course of action in this case might be to lower WEB_CONCURRENCY to 1. Seeing as it is on a 1X dyno anyway, and the vCPU count is only 1 there isn't too much benefit to having Puma run with multiple workers. The Puma worker count is usually the largest consumer of memory, so if you can lower the worker count and perhaps consider increasing the thread count you can often get some good savings.

Hope that helps,
Steven"
