### ISSUE TITLE
Refactor Article from a D on Code Climate

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#615]
https://codeclimate.com/github/BOWiki/BOW/Article

**Comment by campgurus** [comment]
We probably have similar repetition in other models, like Follows.  What is the answer? create a helper method that can be repeated? Maybe one that compares values from the last 30 days to the most recent 30 days and returns a percentage?

**Comment by trystant** [comment]
The repeated queries should be [scopes](http://guides.rubyonrails.org/active_record_querying.html#scopes). Anywhere where the same query is called in multiple places, that should be refactored into a scope.

**Comment by trystant** [comment]
For some reason, Article isn't showing up in the results anymore. I've opened a ticket with CodeClimate

**Comment by trystant** [comment]
Well, the [article](https://codeclimate.com/github/BOWiki/BOW/app/models/article.rb) is showing up now, but it is now a "C", which is progress. We can close this ticket for the time being
