### ISSUE TITLE
new articles using subject model friendly urls not working

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#67]
need to adjust friendly url to use the associated model name for the url

**Comment by campgurus** [comment]
this is a relatively simple fix in the app.  Just adding:

def subject_name
		self.subjects.first.name
  end

to the articles model and  changing the slug generator to:
	extend FriendlyId
	friendly_id :subject_name, use: [:slugged, :finders]

works. However, rspec fails because the subject is not created b4 it is called in the Factory.

**Comment by campgurus** [comment]
this error still occurs. I have saved it to a new branch called fix_friendly_id.

**Comment by trystant** [comment]
This isn't just an rspec problem. Let's take a look here.
<img width="311" alt="screenshot 2016-03-13 00 05 03" src="https://cloud.githubusercontent.com/assets/13509/13727026/558b7192-e8af-11e5-8f12-c03dc5e1ee53.png">

**Comment by trystant** [comment]
I think we need more information about the process you're currently using to update the friendly_ids @campgurus. Did you say  you were doing those manually?

**Comment by campgurus** [comment]
Yes.  When a new article is created, no slug is currently generated by friendly_id. so to prettify the url, I do the following steps:
1. visit the admin panel
2. click articles
3. click to edit the new article
4. edit the slug field to be the desired url ending
5. save the article

**Comment by trystant** [comment]
The big issue is that [friendly_id](https://github.com/norman/friendly_id) creates the URL upon the before_validation callback. As a result, we cannot always guarantee that an article will have a subject when creating/saving. There needs to be another URL that is available when the article doesn't have a subject saved yet.

**Comment by trystant** [comment]
This has been pushed to production.
