### ISSUE TITLE
Default Image name & banner information is cut off on Firefox on Debian

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#68]
This was reported to be occurring on Firefox 38.1.0 ("Debian Iceweasel")
![screenshot from 2015-07-30 10-43-31](https://cloud.githubusercontent.com/assets/13509/8987765/a381530a-36b0-11e5-8ab6-5a5b37da6eae.png)

**Comment by trystant** [comment]
We should probably add some multiple browser UI testing into the mix, since none of the main developers currently have Linux on their computers.

**Comment by campgurus** [comment]
this issue is fixed temporarily uploading the default file in conjunction with a specific case.  H/e when we replace that default image, i suspect it will override and the url we are currently using will no longer be valid.

**Comment by trystant** [comment]
I've found the [source][https://github.com/twbs/bootstrap/issues/17694] of this issue and identified a fix;

set the width of the .img-responsive class to 100%

**Comment by trystant** [comment]
This works in staging
<img width="851" alt="screenshot 2016-02-11 04 31 28" src="https://cloud.githubusercontent.com/assets/13509/12973108/5f1125c6-d078-11e5-95a1-870ab63c0999.png">

**Comment by trystant** [comment]
and now in production
<img width="1035" alt="screenshot 2016-02-11 04 34 21" src="https://cloud.githubusercontent.com/assets/13509/12973224/d50bd064-d078-11e5-8e29-7177141f1ae4.png">
