### ISSUE TITLE
New Feedback Survey

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#693]
We continue to get new responses to our survey on next steps for EBWiki.  However, these responses trickle in over time and not all at once.

Given the slowness of gathering responses, It might be more useful ask broader, longer-term questions vs those dealing with specific low-level features.

**Comment by trystant** [comment]
I don't actually think we need to have a new feedback survey. We already have an order of operations based upon the existing survey as well as a boat load of tasks at hand. While I do think that it is good to have continuing feedback, I don't think that we need to spend a bunch of time on a new survey.

If for no other reason, people will not respond if we keep asking questions but never act upon the feedback from those questions. I favor closing this ticket for now.
