### ISSUE TITLE
Map doesn't appear until someone has scrolled to the bottom of the page

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#7]
On a page with lots of pictures, they may never see the map at all, which makes it a bit of a waste. I think that there should be a certain number of rows before the map arrives, somewhere between 5 and 8.

**Comment by trystant** [comment]
Well, here are some arguments against it. It would also be instructive to use Google Analytics to track and see how many people scrolled down to the bottom of the page. Let's not rely on studies, let's collect some data.

**Comment by campgurus** [comment]
I don't know what you mean by appear. if there are a lot of pictures, the number of rows shown is 3.  they can scroll through them, but the idea is that the user can scroll outside the image gallery div to get to the map quickly. but if they don't recognize that they could be scrolling a long time.  Are you saying if the user scrolls a bit they should be prompted to click out side the div to get to map on the bottom part of the page?

**Comment by trystant** [comment]
The pagination and the upcoming tab enhancements have mitigated this issue for the time being.
