### ISSUE TITLE
Perform Brakeman Audit

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#701]
[Brakeman](http://brakemanscanner.org/) is a scanner. We should perform an audit to determine what we need to fix, if anything.

**Comment by trystant** [comment]
Audit was completed. 

The results are [here](https://gist.github.com/trystant/cab8ce80d457dca38f3808acbed17aa5)

We need to investigate the vulnerability and confirm whether we are in fact, vulnerable.

**Comment by jalcine** [comment]
It looks like you're fine (also hey! I watch this repo a lot).

**Comment by campgurus** [comment]
@jalcine good looking out!

**Comment by trystant** [comment]
I was concerned about the `raw` calls in `_main_content.html.erb`, but I haven't been able to prove conclusively that this is a problem.

We're getting a lot more traffic, and some White power groups have noticed us, so I'd like to batten down the hatches.

**Comment by jalcine** [comment]
That's real. If anything, nixing them altogether (if feasible) could make that less of a worry.

**Comment by trystant** [comment]
Yeah, I thought so. It's used for the rich editing piece. Thinking of having people use Markdown instead (OWASP recommendations)

**Comment by trystant** [comment]
...and this is clean.
