### ISSUE TITLE
Display of Agencies in form not using select2

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#712]
not sure why select2 does not seem to be loading. image below:

<img width="913" alt="screen shot 2016-07-12 at 9 21 28 am" src="https://cloud.githubusercontent.com/assets/1260659/16768399/3dc6f1e0-4812-11e6-9c6b-413af46a9c70.png">

The input box should only show the agencies that have been selected. The list should appear only when the user starts typing to add an agency.

**Comment by campgurus** [comment]
Inspecting element reveals some errors:
<img width="1269" alt="screen shot 2016-07-12 at 9 24 54 am" src="https://cloud.githubusercontent.com/assets/1260659/16768488/931f8c9c-4812-11e6-8a1c-543f0ed64e1f.png">

**Comment by trystant** [comment]
This looks like a CORS issue. We can mitigate by using [rack-cors](https://github.com/cyu/rack-cors) to specify hosts which are valid to use.

**Comment by campgurus** [comment]
uh never mind...

<img width="881" alt="screen shot 2016-07-12 at 9 30 59 am" src="https://cloud.githubusercontent.com/assets/1260659/16768708/677c70a4-4813-11e6-950b-cce7a5fb972e.png">

**Comment by trystant** [comment]
What happen?
