### ISSUE TITLE
photos of nearby cases formatting looks off

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#720]
The rows of photos are not lining up appropriately. Here is the link: http://ebwiki.org/articles/darius-cole-garrit

<img width="885" alt="screen shot 2016-07-16 at 12 16 21 pm" src="https://cloud.githubusercontent.com/assets/1260659/16895847/60dd605c-4b4f-11e6-9e28-9c0c307bd842.png">

**Comment by trystant** [comment]
This has been fixed.
![screen shot 2017-04-10 at 3 15 25 pm](https://cloud.githubusercontent.com/assets/13509/24878299/93ad0f12-1e00-11e7-872a-0f32423537fc.png)
