### ISSUE TITLE
Analytics treating https and http identical pages as separate

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#797]
see screenshot below
<img width="396" alt="screen shot 2016-08-16 at 8 42 17 pm" src="https://cloud.githubusercontent.com/assets/1260659/17720718/1a3c2eec-63f2-11e6-8a5c-53176e6cd1fe.png">

**Comment by trystant** [comment]
That's the difference. We can modify the data so that they're the same, or we can use a legend to indicate that this URL is secure. Over time the insecure URLs will disappear.

**Comment by campgurus** [comment]
I think we let time take care of it in this case.
