### ISSUE TITLE
Heroku Memory Issues

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#821]
Checking the Heroku admin, it looks like we are running into memory limitations with our instance. 1662 OutOfMemory errors in a 24 hour period isn't optimal, by any stretch. 
<img width="1440" alt="screenshot 2016-09-18 15 01 23" src="https://cloud.githubusercontent.com/assets/13509/18618280/2175be34-7db1-11e6-8456-806e54d3acd0.png">

This isn't sustainable and needs to be fixed.

**Comment by campgurus** [comment]
Just curious, are we also seeing this issue via New Relic?

**Comment by trystant** [comment]
I honestly don't know. I'd trust Heroku before Newrelic on the matter. We may also need to adjust the Newrelic config to catch for that.

**Comment by rlgreen91** [comment]
How exactly do you plan to fix it?  I'm assuming that we'll see what memory optimizations we can make first before upping the limitations, right?

**Comment by trystant** [comment]
Well, I think the first things is to check for memory leaks, then look into memory optimizations, and then finally upping limitations if neither of the other routes prove to be productive.

**Comment by trystant** [comment]
@campgurus @rlgreen91 
I've started to do some benchmarking and also found this Heroku guide on [ruby memory](https://devcenter.heroku.com/articles/ruby-memory-use#memory-leaks). I'll be following the instructions therein to identify potential leaks

**Comment by trystant** [comment]
This still needs work. After the most recent restart, this is the memory profile on the production box
![screenshot 2017-08-21 at 2 14 46 am](https://user-images.githubusercontent.com/13509/29505875-c4aa7c8e-8616-11e7-81f2-396d583193aa.png)

**Comment by rlgreen91** [comment]
@trystant Yeah, that's the guide I mentioned in Slack.  I'm planning to tackle #870 later this week, probably tomorrow.

**Comment by trystant** [comment]
So, the moving of the ahoy data wasn't a long term solution. There is a spike that happens a few hours after the server restarts. I'm going to investigate some other options, including the [derailed benchmark](https://blog.codeship.com/debugging-a-memory-leak-on-heroku/) gem.

**Comment by trystant** [comment]
Before going through the derailed benchmark gem, I'm going to inventory the project's gems to see if we need everything that's in there.

**Comment by trystant** [comment]
I've removed two gems so far. I'll continue working on #991 and tying it to the status of this project. At this point there's still the memory increase after a server restart. Looking into what `oink` has to offer.

**Comment by trystant** [comment]
Having installed `oink` and configured it to be in production, there already appears to be a discrepancy. There are only 66 states in the database, but the number of states is increasing. Here are some entries:

```
2017-08-26T11:29:56.186881+00:00 app[web.1]: Oink Action: articles#show
2017-08-26T11:29:56.187028+00:00 app[web.1]: Memory usage: 1442188 | PID: 6
2017-08-26T11:29:56.187106+00:00 app[web.1]: Instantiation Breakdown: Total: 458 | State: 261 | Article: 186 | Category: 6 | Link: 2 | Comment: 1 | Subject: 1 | Agency: 1
2017-08-26T11:29:56.187144+00:00 app[web.1]: Oink Log Entry Complete
```

I think that multiple invocations of `State.all` in the views are responsible.

**Comment by trystant** [comment]
I'm following the instructions on this StackOverflow [post](https://stackoverflow.com/questions/8986144/using-oink-gem-with-heroku/14145299#14145299) on using oink and Heroku. I will attempt to parse the log files for data later this evening.

**Comment by trystant** [comment]
Attempted to parse the production logs, the output I got was:
```
scorintha:~/workspace (master) $ oink --format verbose --threshold 0 log/production-oink.log                                                                        
---- MEMORY THRESHOLD ----
THRESHOLD: 0 MB

-- REQUESTS --

-- SUMMARY --
Worst Requests:

Worst Actions:

Aggregated Totals:
```

I will be exploring more to see if there's something I need to adjust in order to get more info from the logs.

**Comment by trystant** [comment]
So it looks like [oink](https://github.com/noahd1/oink/issues/10) and puma aren't going to get along well.  This also explains how/why oink only reports a 20 MB gain while Heroku's reporting R14 errors. 

To explain plainly, `puma` uses threads. Oink isn't guaranteed thread safe.

We're going to have to find another path.

**Comment by trystant** [comment]
While reviewing the [Heroku Deploying Rails Applications with the Puma Web Server][https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#workers] document, I came to the realization that without evaluating all of the gems, it is impossible to determine whether the app is thread safe. WIthout being able to certify that the app is threadsafe, I reduced the number of threads to 1 and processes to 3. Whether this will result in more memory being used or not is still up for debate.

**Comment by rlgreen91** [comment]
Ok, so you think that the invocation of State.all is a problem?  Where specifically in the code base is that invocation creating a spike?  Did you create an issue, or should I go ahead and make one address all invocations of State.all?

**Comment by trystant** [comment]
@rlgreen91 I am thinking that there might be a problem in how we're using it. According to oink there were 266 state objects used where we only need 66 at most.. I'm still investigating, though. As it turns out, oink and Heroku don't get together quite as well, so more observation's needed, methinks.

I also found another potential article that could work for the [environment](https://devcenter.heroku.com/articles/log-runtime-metrics):

**Comment by rlgreen91** [comment]
Hmm, that sounds interesting, did you go ahead and enable it?

**Comment by rlgreen91** [comment]
Also, maybe you could specify - there are 266 state objects used?  Does that mean we're creating state objects somewhere?  I took a look through the code base and I only see us use State.all in like four places.  I'm taking some time now to think about how we can optimize those calls, we probably don't need to construct the full state object each time anyways.

Do you have the oink logs?  Can you attach them here?

**Comment by trystant** [comment]
Ladies & gentlemen...may I present a smoking gun!

```
2017-09-06T20:29:37.640555+00:00 heroku[web.1]: source=web.1 dyno=heroku.35759379.ce03532d-4977-4da1-8bcb-8940fd192b23 sample#memory_total=362.36MB sample#memory_rss=359.85MB sample#memory_cache=0.06MB sample#m
emory_swap=2.45MB sample#memory_pgpgin=113748pages sample#memory_pgpgout=21611pages sample#memory_quota=512.00MB
```
First Map Request
```
2017-09-06T20:29:59.539599+00:00 heroku[web.1]: source=web.1 dyno=heroku.35759379.ce03532d-4977-4da1-8bcb-8940fd192b23 sample#load_avg_1m=0.00 sample#load_avg_5m=0.22
2017-09-06T20:29:59.539681+00:00 heroku[web.1]: source=web.1 dyno=heroku.35759379.ce03532d-4977-4da1-8bcb-8940fd192b23 sample#memory_total=448.67MB sample#memory_rss=445.75MB sample#memory_cache=0.50MB sample#memory_swap=2.42MB sample#memory_pgpgin=136883pages sample#memory_pgpgout=22643pages sample#memory_quota=512.00MB
```
Second Map Request
```
2017-09-06T20:35:29.612240+00:00 heroku[web.1]: source=web.1 dyno=heroku.35759379.ce03532d-4977-4da1-8bcb-8940fd192b23 sample#memory_total=463.48MB sample#memory_rss=460.49MB sample#memory_cache=0.57MB sample#memory_swap=2.42MB sample#memory_pgpgin=158836pages sample#memory_pgpgout=40805pages sample#memory_quota=512.00MB
```

**Comment by trystant** [comment]
So, here's an outline of how to resolve this issue.

The maps controller has a simple method:
```
  def index
    @articles = Article.all
end
```

With 3000 cases, that's a lot of information to be sent to the front end for markers for the map. In addition, that query needs to be cached for future requests.

**Comment by trystant** [comment]
I removed an `articles.dup` call in the application_helper. Next up; replacing that `Article.all` with an 'Article.pluck` with the actual columns needed baed on the Gmaps4Rails project.

**Comment by trystant** [comment]
Good morning. While trying to minimize the size of the maps query, I created a "avatar_default_url" column on the article. While that has reduced the number of queries called for the articles, it has not reduced the memory profile. There are three things that are becoming clearer to me:
1. I likely need to review the queries made with every `Model.all` or `Model.find`. I think we're likely being wasteful about how we're retrieving this across the board
2. Reducing bloat on an instance is turning into less of "find the smoking gun and remove it" and more "boy, are there a lot of smoking guns here"
3. I definitely need help on this. I'll reach out to y'all and through channels to see if there are more knowledgeable hands who could simplify this.
4: This article indicates that this whole progress on might be 8 steps forward, 7 steps back

More info available at ["N+1 Queries or Memory Problems: Why not Solve Both?"](https://blog.heroku.com/solving-n-plus-one-queries)

**Comment by trystant** [comment]
Following advice from a couple of previous articles as well as this [presentation](https://www.youtube.com/watch?v=kZcqyuPeDao), I'm reducing the number of `puma` workers to 1.

Also noted here; a general Rails app should take up ~300MB.

**Comment by trystant** [comment]
In the end, upgrading to the latest Heroku stack (cedar-14 to Heroku-16) and reducing the number of puma processes to 1 has resulted in this profile. I think we can close this.

![screenshot 2017-10-03 at 7 58 18 am](https://user-images.githubusercontent.com/13509/31124066-c8a2e0b2-a810-11e7-93bd-bd0a51af18c6.png)
