### ISSUE TITLE
Responsive: Cannot click on links on cases on home page in iPhone

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#850]
When I pull up https://ebwiki.org in an iPhone, I cannot click on any of the case links on the home page.

![img_0178](https://cloud.githubusercontent.com/assets/13509/20618174/b4eccee8-b2bb-11e6-8d87-68ecef7cc4e8.PNG)

@campgurus, does this happen on an Android phone as well?

**Comment by trystant** [comment]
I connected my iPhone to the my Mac with a USB cable and then enabled the `Develop` menu in Safari on my computer by clicking on the `Advanced` in Safari preferences and the "Show Develop menu in menu bar" option.

I then reloaded ebwiki.org in my phone's browser and then switched to Safari on my Mac. Under the develop menu, my phone's name is a menu item. Selecting it and then the submenu "Automatically Show Web Inspector for JSContexts" enables the JS console for the iPhone.

Once I reloaded the page in Safari on iOS, I got these console.log error messages:

```
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 1)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 5)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 5)
[Warning] Unexpected CSS token: : (application-562113aa7cd564752f92c6f2cb9e1daa9d9e4778f3ed475253e6b16861fc693a.css, line 5)
```

(Including a screenshot because it contains the formatted line numbers)
<img width="1218" alt="screenshot 2016-11-25 03 26 18" src="https://cloud.githubusercontent.com/assets/13509/20619040/47f4cc1e-b2c0-11e6-92dc-68535876d375.png">

clicking on one of the console.log errors, I see the following:

<img width="1219" alt="screenshot 2016-11-25 03 26 30" src="https://cloud.githubusercontent.com/assets/13509/20619054/5e2eae5a-b2c0-11e6-8aca-8c2247c4a25e.png">

The question at hand is "Where is that filter line coming from?"

**Comment by trystant** [comment]
@campgurus, I removed those filter directives from `app/assets/stylesheets/bootstrap-mods.scss`, but even with those three lines removed, seven more are being generated in the application.css that is generated by the precompile rake task. This issue here indicates that this shouldn't be a problem, so I'm investigating another possible source:

https://github.com/select2/select2/issues/3304

**Comment by trystant** [comment]
For the record, this also happens in Chrome in iOS

**Comment by rlgreen91** [comment]
I just checked using Chrome on Android - clicking on the picture does cause the name to come up on the picture, and clicking the links below does work.

**Comment by campgurus** [comment]
I see the same as @rlgreen91  in terms of android behavior.

**Comment by trystant** [comment]
This is still happening on iOS. I don't think that the filter from `select2` is the cause, but I do not know what is, for the time being. I'll ask around for potential sources of this problem.

**Comment by trystant** [comment]
After much searching, I came upon the solution to this in this [blog post](https://stackoverflow.com/questions/20204255/anchor-tag-not-working-in-safari-ios-for-iphone-ipod-touch-ipad).  I've pushed this change to staging to test out.

**Comment by trystant** [comment]
This has been fixed and in production.
