### ISSUE TITLE
Make the style for user mailer uniform

### ISSUE THREAD

**Issue by rlgreen91** [BOWiki/BOW#857]
Make the code style in `app/mailers/user_notifier.rb` uniform throughout.

**Comment by trystant** [comment]
What in particular about the style in `app/mailers/user_notifier.rb` should be replicated @rlgreen91 ?

**Comment by rlgreen91** [comment]
I know that I wanted each method to follow a convention of `send_email_type`.  I also think the logging needs to be consistent for each method - log once the email(s) has/have been sent.  That's all I can think of at the moment.

**Comment by trystant** [comment]
How do you feel about taking over the ticket and modifying the mailers as you see fit @rlgreen91 ?

**Comment by rlgreen91** [comment]
Addressed in merged PR #1012
