### ISSUE TITLE
Redo design of title and subtitle on case page

### ISSUE THREAD

**Issue by rlgreen91** [BOWiki/BOW#858]
On each case page, instead of listing the subtitle as "City, State. Date", rearrange to be like this:

Name, Age
Location
Date.

**Comment by trystant** [comment]
This page looks like this on dev.
![screenshot 2017-03-28 at 6 35 45 pm](https://cloud.githubusercontent.com/assets/13509/24430614/6f23f180-13e5-11e7-8c00-520da9f0642c.png)

**Comment by rlgreen91** [comment]
Would it be possible to remove the period after the location?

**Comment by trystant** [comment]
Pushing that period removal to [Staging](https://staging.ebwiki.org).

**Comment by campgurus** [comment]
Looks good!

**Comment by trystant** [comment]
This is in production
