### ISSUE TITLE
Edit Article title is empty

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#86]
If you look at the article title, it's undefined.

!["undefined"](http://grandkru.com/images/no_title.png)

**Comment by trystant** [comment]
Strangely enough, the title on the edit page still shows up as "undefined". I wonder why

**Comment by campgurus** [comment]
the meta tag info needs to be within the meta tag.  like this:

<% meta title: "EBWiki editing the case of #{@article.title}",
     description: "#{@article.overview.truncate(155)}",
     keywords: %w("@article.subjects.first.name police violence people color")
%>

That works for me on local.

**Comment by campgurus** [comment]
I made this change on master and pushed it to staging.  I will leave it to @trystant to push to production if desired.

**Comment by campgurus** [comment]
This is fixed on production
