### ISSUE TITLE
Geolocation is not working

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#881]
I added several cases today and despite entering valid addresses, no latitude/longitude coordinates were generated. I also looked back at a few recent cases and it seems that this issue has existed for some time now, since they were also missing the geolocation.

**Comment by trystant** [comment]
We need to add tests to confirm that geo works as well as add a rake task to autogenerate coordinates for all articles that don't have it (so that if this does happen again, the fix will take a few minutes).

**Comment by campgurus** [comment]
We have a test that purports to test for geocoding of new articles within the model spec article_spec.rb

**Comment by rlgreen91** [comment]
In looking at the test, I see that we check that the article has geocoding - but I can't find where we actually do that.  In `article.rb`, we include `after_validation :geocode` but I can't find any method definition associated with that.  I'll check again, but is there something I'm missing?

**Comment by campgurus** [comment]
I think that method is in the geocoder gem.  https://github.com/alexreisner/geocoder

**Comment by rlgreen91** [comment]
This looks like it is addressed in merged PRs.
