### ISSUE TITLE
gallery images of  nearby cases does not display default pictures 

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#91]
leaving an awkward blank spot instead.  here is an example:

![image](https://cloud.githubusercontent.com/assets/1260659/9211826/843d2aae-4052-11e5-8f64-5aef538ac357.png)

**Comment by campgurus** [comment]
i have added the default image, but now the arrangement of gallery images seems to leave extra space for images as blank space.see image below from http://ebwiki.org/articles/philip-white:
<img width="1211" alt="screen shot 2015-08-28 at 8 43 20 am" src="https://cloud.githubusercontent.com/assets/1260659/9546511/3be6a4a8-4d61-11e5-9650-f77e68de7fc0.png">

**Comment by campgurus** [comment]
This issue is resolved with the new orange is black styling committed here: 7c533e280e20b5c5e2e95cd961a4f33dc62a302e

**Comment by trystant** [comment]
I'm actually going to close this now, since this individual issue is resolved, based upon the current page http://ebwiki.org/articles/philip-white
