### ISSUE TITLE
misaligned case images on index page

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#913]
See image:
<img width="1213" alt="screen shot 2017-05-22 at 1 34 56 am" src="https://cloud.githubusercontent.com/assets/1260659/26309806/75c1c794-3ecc-11e7-9ce9-0cb8c47040f6.png">

**Comment by rlgreen91** [comment]
Hmm, what browser is this in? I'm running Chrome Version 58.0.3029.110 and everything looks fine to me.

**Comment by campgurus** [comment]
It was Chrome.  but Irefreshed the page and the issue seems to have gone away. closing this.

**Comment by rlgreen91** [comment]
Hmm, let's not be too hasty.  Do you remember anything about what you were doing that caused this?  Are you using the same version of Chrome that I am?  I'd like to figure out why this happened - otherwise we can't prevent it happening again.

**Comment by campgurus** [comment]
I don't remember anything specific about what I did other than loading the root page. The Chrome version I am using is: Version 57.0.2987.133 (64-bit).

**Comment by rlgreen91** [comment]
Hmm, alright, I guess we can go ahead and close this then.  We'll just keep an eye out for it happening again.
