### ISSUE TITLE
Extend background color for footer

### ISSUE THREAD

**Issue by rlgreen91** [BOWiki/BOW#963]
On each page, the background color for the footer is truncated.  It should extend the full width of the page just like the header.

**Comment by trystant** [comment]
There is a current fix for this on staging. Here are links to [home](https://staging.ebwiki.org/), [maps](https://staging.ebwiki.org/maps/index) and [case](https://staging.ebwiki.org/articles/lawrence-sanchez) pages.

The footer text is not justified to match the header in alignment. I couldn't figure out a way to have it be aligned within the final div. I do feel that this is still an overall improvement, so if @campgurus and @rlgreen91 are okay, I'll push that to production later today.

**Comment by trystant** [comment]
I'm pushing this up. If needed, we can open another ticket to align the footer text.
