### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by rlgreen91** [BOWiki/BOW#968]
In the Code of Conduct section, it says this: "Link to Code to Code Of Conduct document." - where the phrase "Code of Conduct" is a link.  Remove the first instance of "to Code" so it reads "Link to Code Of Conduct document."  It should still contain the link.

**Comment by vatrudell** [comment]
Hello there, @rlgreen91, I am doing an open source project for school and I was wondering if I could take this documentation fix off your hands. If that okay with you, I am just curious if there is anything pertaining to committing or merging processes I should know about. I'm new to open source and I don't want to mess any of you processes up.

**Comment by rlgreen91** [comment]
Hi @vatrudell, great to hear from you!  So, yes, feel free to jump in!  Since this is a fix to the README, what you can just do the standard clone, make a branch, open a PR process.  This should be one commit, with a message explaining what the commit is.  Open a PR, and we will review it and merge when approved. (Side note: I guess this is the kick in the pants I need to finish our developer's guide).

But yeah, feel free to jump in.  If you want to stick to documentation fixes that's fine, just let me know if you choose something that will be on the site rather than on the README.  If you have any questions, then please feel free to reach out here on GitHub or at my username@gmail.com

**Comment by vatrudell** [comment]
@rlgreen91 Thanks for getting back to me, I will do those things, and take a look at some of your issues
to see if I can help. Side note, I like your email

**Comment by rlgreen91** [comment]
Addressed in PR #1036
