### ISSUE TITLE
Remove method `send_update_email`

### ISSUE THREAD

**Issue by rlgreen91** [BOWiki/BOW#986]
Remove method `send_update_email` and the associated test from `app/mailers/user_notifier.rb` and `spec/mailers/user_notifier_spec.rb`.  As far as I can tell, this method is not used in any other file and is essentially identical to `send_followers_email`.

**Comment by rlgreen91** [comment]
@trystant @campgurus Can you guys shed some light on what this method is for?  Like I said, it doesn't appear to be used anywhere.  I'd like your confirmation that we can delete this code.

**Comment by trystant** [comment]
@rlgreen91 @campgurus This looks like a precursor to `send_followers_email`, based on this comment:
`# send a signup email to the user, pass in the user object that   contains the user's email address`
I think we can let this go.

**Comment by trystant** [comment]
This has been pushed to production. We can close this.
